<?php

namespace Ebbe\FileRepositoryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FileLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileLocationRepository extends EntityRepository
{
}
