parameters:
#    ebbe_doccon.example.class: Ebbe\DocconBundle\Example

services:
#    ebbe_doccon.example:
#        class: %ebbe_doccon.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    ebbe_doccon.admin.delivery:
        class: Ebbe\DocconBundle\Admin\DeliveryAdmin
        arguments: [~, Ebbe\DocconBundle\Entity\Delivery, EbbeDocconBundle:DeliveryAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Delivery}
