<?php

namespace Proxies\__CG__\Ebbe\DocconBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Delivery extends \Ebbe\DocconBundle\Entity\Delivery implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'originatorOrg', 'originatorAuthor', 'originatorOwner', 'docHasIssues', 'docDeleted', 'docResubmitted', 'docForReporting', 'serialNumber', 'docExisting', 'project', 'projectPhase', 'projectSubphase', 'projectPackage', 'idPrimavera', 'originatorDocId', 'originatorDocVersion', 'hasPreviousDelivery', 'previousDelivery', 'title', 'recipientOrganisation', 'recipientGroup', 'recipientLead', 'formality', 'reviewProcess', 'reviewCurrentStage', 'categoryApp4', 'refSetNumber', 'relevanceSSrNsOd', 'docLocation');
        }

        return array('__isInitialized__', 'id', 'originatorOrg', 'originatorAuthor', 'originatorOwner', 'docHasIssues', 'docDeleted', 'docResubmitted', 'docForReporting', 'serialNumber', 'docExisting', 'project', 'projectPhase', 'projectSubphase', 'projectPackage', 'idPrimavera', 'originatorDocId', 'originatorDocVersion', 'hasPreviousDelivery', 'previousDelivery', 'title', 'recipientOrganisation', 'recipientGroup', 'recipientLead', 'formality', 'reviewProcess', 'reviewCurrentStage', 'categoryApp4', 'refSetNumber', 'relevanceSSrNsOd', 'docLocation');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Delivery $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginatorOrg($originatorOrg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginatorOrg', array($originatorOrg));

        return parent::setOriginatorOrg($originatorOrg);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginatorOrg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginatorOrg', array());

        return parent::getOriginatorOrg();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginatorAuthor($originatorAuthor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginatorAuthor', array($originatorAuthor));

        return parent::setOriginatorAuthor($originatorAuthor);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginatorAuthor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginatorAuthor', array());

        return parent::getOriginatorAuthor();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginatorOwner($originatorOwner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginatorOwner', array($originatorOwner));

        return parent::setOriginatorOwner($originatorOwner);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginatorOwner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginatorOwner', array());

        return parent::getOriginatorOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocHasIssues($docHasIssues)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocHasIssues', array($docHasIssues));

        return parent::setDocHasIssues($docHasIssues);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocHasIssues()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocHasIssues', array());

        return parent::getDocHasIssues();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocDeleted($docDeleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocDeleted', array($docDeleted));

        return parent::setDocDeleted($docDeleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocDeleted', array());

        return parent::getDocDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocResubmitted($docResubmitted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocResubmitted', array($docResubmitted));

        return parent::setDocResubmitted($docResubmitted);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocResubmitted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocResubmitted', array());

        return parent::getDocResubmitted();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocForReporting($docForReporting)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocForReporting', array($docForReporting));

        return parent::setDocForReporting($docForReporting);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocForReporting()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocForReporting', array());

        return parent::getDocForReporting();
    }

    /**
     * {@inheritDoc}
     */
    public function setSerialNumber($serialNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerialNumber', array($serialNumber));

        return parent::setSerialNumber($serialNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getSerialNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerialNumber', array());

        return parent::getSerialNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocExisting($docExisting)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocExisting', array($docExisting));

        return parent::setDocExisting($docExisting);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocExisting()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocExisting', array());

        return parent::getDocExisting();
    }

    /**
     * {@inheritDoc}
     */
    public function setProject($project)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProject', array($project));

        return parent::setProject($project);
    }

    /**
     * {@inheritDoc}
     */
    public function getProject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProject', array());

        return parent::getProject();
    }

    /**
     * {@inheritDoc}
     */
    public function setProjectPhase($projectPhase)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjectPhase', array($projectPhase));

        return parent::setProjectPhase($projectPhase);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjectPhase()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjectPhase', array());

        return parent::getProjectPhase();
    }

    /**
     * {@inheritDoc}
     */
    public function setProjectSubphase($projectSubphase)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjectSubphase', array($projectSubphase));

        return parent::setProjectSubphase($projectSubphase);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjectSubphase()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjectSubphase', array());

        return parent::getProjectSubphase();
    }

    /**
     * {@inheritDoc}
     */
    public function setProjectPackage($projectPackage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjectPackage', array($projectPackage));

        return parent::setProjectPackage($projectPackage);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjectPackage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjectPackage', array());

        return parent::getProjectPackage();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPrimavera($idPrimavera)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPrimavera', array($idPrimavera));

        return parent::setIdPrimavera($idPrimavera);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPrimavera()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPrimavera', array());

        return parent::getIdPrimavera();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginatorDocId($originatorDocId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginatorDocId', array($originatorDocId));

        return parent::setOriginatorDocId($originatorDocId);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginatorDocId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginatorDocId', array());

        return parent::getOriginatorDocId();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginatorDocVersion($originatorDocVersion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginatorDocVersion', array($originatorDocVersion));

        return parent::setOriginatorDocVersion($originatorDocVersion);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginatorDocVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginatorDocVersion', array());

        return parent::getOriginatorDocVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setHasPreviousDelivery($hasPreviousDelivery)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHasPreviousDelivery', array($hasPreviousDelivery));

        return parent::setHasPreviousDelivery($hasPreviousDelivery);
    }

    /**
     * {@inheritDoc}
     */
    public function getHasPreviousDelivery()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHasPreviousDelivery', array());

        return parent::getHasPreviousDelivery();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreviousDelivery($previousDelivery)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreviousDelivery', array($previousDelivery));

        return parent::setPreviousDelivery($previousDelivery);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreviousDelivery()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreviousDelivery', array());

        return parent::getPreviousDelivery();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecipientOrganisation($recipientOrganisation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecipientOrganisation', array($recipientOrganisation));

        return parent::setRecipientOrganisation($recipientOrganisation);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecipientOrganisation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecipientOrganisation', array());

        return parent::getRecipientOrganisation();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecipientGroup($recipientGroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecipientGroup', array($recipientGroup));

        return parent::setRecipientGroup($recipientGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecipientGroup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecipientGroup', array());

        return parent::getRecipientGroup();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecipientLead($recipientLead)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecipientLead', array($recipientLead));

        return parent::setRecipientLead($recipientLead);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecipientLead()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecipientLead', array());

        return parent::getRecipientLead();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormality($formality)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormality', array($formality));

        return parent::setFormality($formality);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormality()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormality', array());

        return parent::getFormality();
    }

    /**
     * {@inheritDoc}
     */
    public function setReviewProcess($reviewProcess)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReviewProcess', array($reviewProcess));

        return parent::setReviewProcess($reviewProcess);
    }

    /**
     * {@inheritDoc}
     */
    public function getReviewProcess()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReviewProcess', array());

        return parent::getReviewProcess();
    }

    /**
     * {@inheritDoc}
     */
    public function setReviewCurrentStage($reviewCurrentStage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReviewCurrentStage', array($reviewCurrentStage));

        return parent::setReviewCurrentStage($reviewCurrentStage);
    }

    /**
     * {@inheritDoc}
     */
    public function getReviewCurrentStage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReviewCurrentStage', array());

        return parent::getReviewCurrentStage();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoryApp4($categoryApp4)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoryApp4', array($categoryApp4));

        return parent::setCategoryApp4($categoryApp4);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoryApp4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoryApp4', array());

        return parent::getCategoryApp4();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefSetNumber($refSetNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefSetNumber', array($refSetNumber));

        return parent::setRefSetNumber($refSetNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefSetNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefSetNumber', array());

        return parent::getRefSetNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelevanceSSrNsOd($relevanceSSrNsOd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelevanceSSrNsOd', array($relevanceSSrNsOd));

        return parent::setRelevanceSSrNsOd($relevanceSSrNsOd);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelevanceSSrNsOd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelevanceSSrNsOd', array());

        return parent::getRelevanceSSrNsOd();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocLocation($docLocation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocLocation', array($docLocation));

        return parent::setDocLocation($docLocation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocLocation', array());

        return parent::getDocLocation();
    }

}
